# Generated by Django 3.0.5 on 2020-04-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthtrends', '0002_auto_20200415_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
