# Generated by Django 3.0.5 on 2020-04-15 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthtrends', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GUserCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
                ('id_token', models.CharField(max_length=1000)),
                ('valid', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
