# Generated by Django 3.0.5 on 2020-04-15 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('account', '0002_email_max_length'),
        # ('socialaccount', '0003_extra_data_default_dict'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('healthtrends', '0008_auto_20200415_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='GglCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(default='', max_length=1000)),
                ('access_token', models.CharField(default='', max_length=1000)),
                ('id_token', models.CharField(default='', max_length=1000)),
                ('valid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
