# Generated by Django 3.0.5 on 2020-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtrends', '0009_auto_20200415_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gglcred',
            name='valid',
        ),
        migrations.AddField(
            model_name='gglcred',
            name='invalid',
            field=models.BooleanField(default=True),
        ),
    ]
