# Generated by Django 3.0.5 on 2020-04-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthtrends', '0010_auto_20200415_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=200)),
                ('spreadsheet', models.CharField(max_length=200)),
                ('number_runs', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('geographic_area', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_data', models.DateField()),
                ('terms', models.CharField(max_length=10000)),
            ],
        ),
    ]
